export const UPDATE_GLOBAL_SETTINGS = 'UPDATE_GLOBAL_SETTINGS';

export const GET_OPEN_SLOTS = 'GET_OPEN_SLOTS';
export const SCHEDULE_APPOINTMENT = 'SCHEDULE_APPOINTMENT';
export const PATIENT_LOOKUP = "PATIENT_LOOKUP";
export const PATIENT_SEARCH = "PATIENT_SEARCH";